In [24]:
import numpy as np
import math
import pylab as plt
def sigma(z):
    return 1/(1+np.exp(-z))
def L(y,a):
    return -(y*math.log10(a)+(1-y)*math.log(1-a))


In [33]:
alpha=0.1
X=np.array([[5 ,1],[4, 2],[3,1]])
X=X.transpose()
Y=np.array([1,0,1])
n=X.shape[0]
m=X.shape[1]
dZ=np.zeros((n,m))
W=np.zeros((1,n))
b=0


In [34]:
for i in range(0,5):
    Z= np.dot(W,X)+b
    A=sigma(Z)
    dZ= A-Y    
    db = (1/m)*np.sum(dZ)
    dW=1/m*np.dot(X,dZ.transpose())
    W=W-alpha*dW.transpose()
    b=b-alpha*db
    J=1/m*A.sum()

In [31]:
W 

array([[  3.77641378, -13.48894624]])

In [29]:
W

array([[  3.30824559, -11.62060509]])

In [35]:
W

array([[ 0.15278314, -0.05753684]])