In [2]:
%pylab inline
import scipy
from scipy.fftpack import fft, rfft,fftshift

Populating the interactive namespace from numpy and matplotlib


In [3]:
y=[1,1,0,0,0,0,0,0,1,1,1]
a=np.zeros(6)
b=np.zeros(6)
for n in range(0,6):
    for r in range (0,11):
        a[n]=a[n]+y[r]*cos(2*np.pi*(r+1)*(n)/11)
        if n<5:
            b[n+1]=b[n+1]+y[r]*sin(2*np.pi*(r+1)*(n+1)/11)
    a[n]=a[n]*2/11
    b[n]=b[n]*2/11
b[0]=0
b[5]=0

In [4]:
a

array([ 0.90909091,  0.63878856,  0.09474701, -0.2188392 , -0.10806384,
        0.13882202])

In [5]:
b

array([ 0.00000000e+00, -2.26205469e-16, -3.11109827e-16, -5.57501169e-16,
       -8.03892512e-16,  0.00000000e+00])

In [6]:
t = np.zeros(11)
for r in range(1,12):
    z=0
    for n in range(1,5):
        z+=a[n]*cos(2*np.pi*r*(n)/11)+b[n]*sin(2*np.pi*r*(n)/11)
    t[r-1]=z+a[0]/2+a[5]/2*cos(np.pi*r)        

In [7]:
k=rfft(y)

In [8]:
k

array([ 5.        ,  2.95560724,  1.89945344,  0.21647632,  0.47401702,
        0.17129236, -1.19136455,  0.38921723, -0.44918062, -0.73259315,
        0.21510876])

In [9]:
t

array([ 1.06378774,  0.95262649,  0.02149808,  0.01174226, -0.04965458,
        0.08916744, -0.12707976,  0.1603201 ,  0.81380447,  1.20260977,
        0.79176697])